backend:
  name: git-gateway
  branch: gh-pages # Branch to update (optional; defaults to master)
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "paginas" # Used in routes, e.g., /admin/collections/blog
    label: "Páginas" # Used in the UI
    folder: "_pages/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Formato", name: "layout", widget: "hidden", default: "default"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Extracto", name: "excerpt", widget: "string"}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
      - {label: "Sitemap", name: "sitemap", widget: "hidden", default: "false"}

