backend:
  name: git-gateway
  branch: gh-pages # Branch to update (optional; defaults to master)
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "paginas" # Used in routes, e.g., /admin/collections/blog
    label: "Páginas" # Used in the UI
    folder: "_pages/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Formato", name: "layout", widget: "hidden", default: "default"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Extracto", name: "excerpt", widget: "string"}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
      - {label: "Sitemap", name: "sitemap", widget: "boolean", default: false}
      - {label: "Permalink", name: "permalink", widget: "string", default: "{{slug}}"}
  - name: "listas"
    label: "Listas"
    files:
      - label: "Investigadores"
        name: "investigadores"
        file: "_data/investigadores.yml"
        extension: yml
        editor:
          preview: false
        fields:
          - label: Investigador
            name: miembros
            widget: list
            fields:
              - {label: Nombre, name: name, widget: string}
              - {label: Foto, name: photo, widget: image}
              - {label: Info, name: info, widget: string}
              - {label: Email, name: email, widget: string}
              - {label: Numero Educ, name: number_educ, widget: number}
              - {label: Educación 1, name: education1, widget: text, required: false}
              - {label: Educación 2, name: education2, widget: text, required: false}
              - {label: Educación 3, name: education3, widget: text, required: false}
              - {label: Educación 4, name: education4, widget: text, required: false}
              - {label: Educación 5, name: education5, widget: text, required: false}
      - label: "Noticias"
        name: "noticias"
        file: "_data/news.yml"
        extension: yml
        fields:
          - label: Entrada
            name: entradas
            widget: list
            editor:
              preview: false
            fields:
              - {label: Título, name: headline, widget: markdown}
              - {label: Fecha, name: date, widget: date, format: "DD/MM/YYYY"}
      - label: "Publicaciones"
        name: "publicaciones"
        file: "_data/publications.yml"
        extension: yml
        editor:
          preview: false
        fields:
        - label: "papers"
          name: "papers"
          widget: list
          editor:
            preview: false
          fields:
            - {label: Título, name: title, widget: string}
            - {label: Foto, name: image, widget: image, required: false, hint: "Solo aparece si el paper está destacado."}
            - {label: Descripción, name: description, widget: text}
            - {label: Autores, name: authors, widget: string, hint: "Formato a preferencia, pero que calce con los demás papers."}
            - label: Link
              name: link
              widget: object
              fields:
              - {label: URL, name: url, widget: string}
              - {label: "Mostrar como", name: display, widget: string, hint: "Texto que aparece como si fuera el link."}
            - label: "¿Destacar?"
              name: highlight
              default: 0
              min: 0
              max: 1
              step: 1
              valueType: int
              widget: number
              required: true
              hint: "1 significa destacar, 0 significa no destacar."
            - {label: "En los medios 1", name: news, widget: text, required: false, hint: "Aquí usualmente pones un link en HTML a publicaciones, menciones o cosas relacionadas. Puedes usar el 2 y el 3 si necesitas mas."}
            - {label: "En los medios 2", name: news1, widget: text, required: false}
            - {label: "En los medios 3", name: news2, widget: text, required: false}
        - label: "libros"
          name: "libros"
          widget: list
          editor:
            preview: false
          fields:
            - {label: Título, name: title, widget: string}
            - {label: Foto, name: image, widget: image, required: false, hint: "Solo aparece si el libro está destacado."}
            - {label: Descripción, name: description, widget: text}
            - {label: Autores, name: authors, widget: string, hint: "Formato a preferencia, pero que calce con los demás libros."}
            - {label: "En los medios 1", name: news, widget: text, required: false, hint: "Aquí usualmente pones un link en HTML a publicaciones, menciones o cosas relacionadas. Puedes usar el 2 y el 3 si necesitas mas."}
            - {label: "En los medios 2", name: news1, widget: text, required: false}
            - {label: "En los medios 3", name: news2, widget: text, required: false}
